import Header from "@/components/Navigation/Header";
import "./globals.css";
import Footer from "@/components/Navigation/Footer";
import ChatBot from "@/components/Navigation/ChatBot";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        {children}
        <Footer />
        <ChatBot />
      </body>
    </html>
  );
}
