import Header from "@/components/Navigation/Header";
import "./globals.css";
import Footer from "@/components/Navigation/Footer";
import ChatBot from "@/components/Navigation/ChatBot";
import { Lato } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased`}>
        <Header />
        {children}
        <Footer />
        <ChatBot />
      </body>
    </html>
  );
}
