import FAQs from "@/components/Sections/Home/FAQs";
import FeaturedProjects from "@/components/Sections/Home/FeaturedProjects";
import Hero from "@/components/Sections/Home/Hero";
import HeroNew from "@/components/Sections/Home/HeroNew";
import Schedule from "@/components/Sections/Home/Schedule";
import { HomeFAQs } from "@/constants";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <main>
      {/* <Hero /> */}
      <HeroNew />
      <FeaturedProjects />
      <Schedule />
      <FAQs faqs={HomeFAQs} />
    </main>
  );
};

export default HomePage;
